### ISSUE TITLE
Failed to use consumer in MediaIPC.

### ISSUE THREAD

**Issue by jonike** [adamrehn/UE4Capture#1]
Hi, There.
I successfully ran the UE4Capture game from the tutorial, but the consumer program in the MediaIPC example could not successfully process the capture data of the UE4Capture plugin. Tracking MediaConsumer.cpp in the MediaIPC library on line 42: this->statusMutex= consumerMutex(names.statusMutex) is always unsuccessful.

My environment: 
windows 10 x64
UE4.17 x64

Could you fix that? thanks.

**Comment by adamrehn** [comment]
As stated in the README, the UE4Capture plugin requires Unreal Engine **4.19.0 or newer**. It will not work with Unreal Engine 4.17.

**Comment by jonike** [comment]
Thanks, it has been resolved. Administrator privileges are required to start the program.
