### ISSUE TITLE
Broken in 4.21

### ISSUE THREAD

**Issue by Wallby** [adamrehn/UE4Capture#2]
As of UE4 version 4.21 the MediaSceneCapture module has undergone some refactoring.

MovieSceneCaptureProtocolRegistry.h is gone and is now replaced by MovieSceneCaptureProtocolBase.h.

I gave fixing it a shot, but somehow the consumer did not detect the end of the capture.
For the implementation though, I used all of your code from the `FrameCaptureProtocol` class and put that into a new class that derives from the `UFrameGrabberProtocol` class (for an example of how to use it, see the new `UVideoCaptureProtocol` class, which derives from the same class.

The `UMovieSceneCapture` object no longer has a `CaptureType `variable, but instead two new variables `ImageCaptureProtocol `and `AudioCaptureProtocol`.

Anyway, that is all I've figured out so far, though for my needs I am probably going to use something other than this plugin. In case you want to fix it though, I'm letting you know all I've figured out.

**Comment by adamrehn** [comment]
Thanks for looking into this! 4.21 and 4.22 support have been on my TODO list for a while now, although I'm planning on delving into the source code for the official [Pixel Streaming](https://docs.unrealengine.com/en-us/Platforms/PixelStreaming) plugin first to determine the feasibility of enabling Linux and macOS support for that, which would make the UE4Capture plugin redundant. If that turns out to be too complex (e.g. requires modifications to the RHIs for each platform) then I'll focus my efforts on updating UE4Capture instead.

**Comment by revis3d** [comment]
> I gave fixing it a shot, but somehow the consumer did not detect the end of the capture.

Hi Wallby, can you share your solution? I was trying to do what you did but I didn't manage to compile the VideoCapture.cpp without errors. 

I am looking for a solution to record video and audio from UE4 and simply write that to an encoded file locally. My idea was to put the consumer functionality right into the producer plugin.

> Anyway, that is all I've figured out so far, though for my needs I am probably going to use something other than this plugin.

Have you found some other solution that is working for you?

**Comment by Wallby** [comment]
@revis3d this post is a while old. As far as I can tell, it looks like I shared all that I figured out. If you want to give it a shot, I'd recommend trying what I did, and follow your error log from there.

Cheers.

**Comment by adamrehn** [comment]
Just commenting here for anyone who stumbles upon this in the future: the UE4Capture plugin is deprecated and all development effort has now shifted to [Pixel Streaming for Linux](https://adamrehn.com/articles/pixel-streaming-in-linux-containers/) instead, which is the recommended solution for remote streaming. Local capture scenarios are typically best served by other tools, both within the Unreal Engine itself and at a system level.

**Comment by revis3d** [comment]
@Wallby Thank you for the input. I fixed this for UE4.24 and created a pull request.
